<?php

namespace MtsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KorisnikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KorisnikRepository extends EntityRepository
{
}
