<?php

namespace MtsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TempKorisnikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempKorisnikRepository extends EntityRepository
{
}
