<?php

namespace MtsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TlistRepository extends EntityRepository
{
}
