<?php

namespace MtsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ToDoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToDoListRepository extends EntityRepository
{
}
